apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: image: 428613119876.dkr.ecr.us-east-1.amazonaws.com/my-app:${{ github.sha }}
        ports:
        - containerPort: 80